export const pagination = {
  display: 'flex',
  maxW: 'none',
  mx: 0,
  alignItems: 'center',
  justifyContent: 'center',
  userSelect: 'none',
  padding: 0,
  margin: 0,
  mt: 8,
  '.rc-pagination-item': {
    a: {
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'center',
      bg: 'main_white',
      color: 'gray.1400',
      fontSize: '12px',
      border: '1px solid',
      borderColor: 'blue.100',
      borderRadius: '4px',
      h: 'full',
      _hover: {
        bg: 'blue.500',
        color: 'main_white',
      },
    },
    h: '8',
    w: '8',
    m: '0',
    mx: '1',
    border: 'none',
    bg: 'main_white',
  },
  '.rc-pagination-item-active': {
    a: {
      bg: 'blue.500',
      color: 'main_white',
      border: 'none',
    },
  },
  '.rc-pagination-jump-next': {
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    bg: 'blue.50',
    m: '0',
    h: '8',
    w: '8',
    borderRadius: '4px',
  },
  '.rc-pagination-jump-prev': {
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    bg: 'blue.50',
    m: '0',
    h: '8',
    w: '8',
    borderRadius: '4px',
  },
  '.rc-pagination-prev': {
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    h: '8',
    w: '8',
    minW: '5',
    mr: '3',
    bg: 'blue.500',
    color: 'main_white',
    cursor: 'pointer',
    borderRadius: '4px',
  },
  '.rc-pagination-next': {
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    h: '8',
    w: '8',
    ml: '3',
    bg: 'blue.500',
    color: 'main_white',
    cursor: 'pointer',
    borderRadius: '4px',
  },
  '.rc-pagination-disabled': {
    display: 'none',
  },
}
